enum NotificationType {
  NORMAL = "NORMAL",
  INVITATION = "INVITATION",
  ACCEPTED_INVITATION = "ACCEPTED_INVITATION",
  DECLINED_INVITATION = "DECLINED_INVITATION",
  INVITATION_CREATOR = "INVITATION_CREATOR",
  WORKSPACE_TITLE_UPDATE = "WORKSPACE_TITLE_UPDATE",
  DELETE_WORKSPACE = "DELETE_WORKSPACE",
  DELETE_WORKSPACE_CREATOR = "DELETE_WORKSPACE_CREATOR",
  APPOINT_ADMIN = "APPOINT_ADMIN",
  APPOINT_ADMIN_ACCEPTED = "APPOINT_ADMIN_ACCEPTED",
  APPOINT_ADMIN_DECLINED = "APPOINT_ADMIN_DECLINED",
  APPOINT_ADMIN_CREATOR = "APPOINT_ADMIN_CREATOR",
}

export default NotificationType;
